"""empty message

Revision ID: 0d55093d5697
Revises: 
Create Date: 2021-07-02 13:56:37.409943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d55093d5697'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('album_name', sa.String(length=255), nullable=True),
    sa.Column('artist_spotify_id', sa.String(length=255), nullable=False),
    sa.Column('song_spotify_id', sa.String(length=255), nullable=False),
    sa.Column('danceability', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('energy', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=False),
    sa.Column('valence', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('tempo', sa.Numeric(asdecimal=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_spotify_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vibes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=99), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vibe_member',
    sa.Column('vibe_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['vibe_id'], ['vibes.id'], ),
    sa.PrimaryKeyConstraint('vibe_id', 'song_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vibe_member')
    op.drop_table('vibes')
    op.drop_table('users')
    op.drop_table('songs')
    # ### end Alembic commands ###
