"""empty message

Revision ID: b97fe11b3e05
Revises: 
Create Date: 2021-06-30 17:54:48.318804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97fe11b3e05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vibes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=99), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('album_name', sa.String(length=255), nullable=True),
    sa.Column('vibe_id', sa.Integer(), nullable=True),
    sa.Column('artist_spotify_id', sa.String(length=255), nullable=False),
    sa.Column('song_spotify_id', sa.String(length=255), nullable=False),
    sa.Column('danceability', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('energy', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=False),
    sa.Column('valence', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('tempo', sa.Numeric(asdecimal=False), nullable=False),
    sa.ForeignKeyConstraint(['vibe_id'], ['vibes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_spotify_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    op.drop_table('vibes')
    op.drop_table('users')
    # ### end Alembic commands ###
